// Generated declarations for imported RPG Urban project tiles.
namespace myTiles {
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanDoorCandidates0283 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanDoorCandidates0284 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanDoorCandidates0285 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0008 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0009 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0010 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0011 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0012 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0013 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0014 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0015 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0035 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0036 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0037 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0038 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0039 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0040 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0041 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0042 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0062 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0063 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0064 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0065 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0066 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0067 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0068 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanPavement0069 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0432 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0433 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0434 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0435 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0436 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0437 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0438 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0439 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0440 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0441 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0442 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0459 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0460 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0461 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0462 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0463 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0464 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0465 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0466 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0467 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0468 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanRoad0469 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0328 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0329 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0330 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0331 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0332 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0335 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0336 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0337 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0338 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0339 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0359 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0360 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0361 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0362 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0363 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0364 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0365 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanSavehouseFacade0366 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0164 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0165 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0166 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0168 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0169 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0190 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0221 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0222 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0223 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0250 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0254 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0279 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0280 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0305 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0306 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanStreetProps0307 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanVegetation0259 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanVegetation0260 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanVegetation0265 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanVegetation0286 = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanVegetation0287 = image.ofBuffer(hex``);
}
