// Generated declarations for placement-ready RPG Urban project tiles.
namespace myTiles {
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0164Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0165Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0166Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0168Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0169Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0190Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0223Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0250Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0254Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0279Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0280Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0305Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0306Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0221Road = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0222Road = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStreetProps0307Road = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyVegetation0259Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyVegetation0260Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyVegetation0265Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyVegetation0286Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyVegetation0287Pavement = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStorefrontLeft = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStorefrontMiddle = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStorefrontRight = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStorefrontNarrowLeft = image.ofBuffer(hex``);
  //% fixedInstance jres blockIdentity=images._tile
  export const rpgUrbanReadyStorefrontNarrowRight = image.ofBuffer(hex``);
}
